# Site settings
title: EIC
email: eic@0x19.net
description: > # this means to ignore newlines until "baseurl:"
url: "http://eic.0x19.net" # the base hostname & protocol for your site

twitter_username: jekyllrb
github_username: eic-network

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    
defaults:
  -
    scope:
      type: projects
    values:
      layout: project
      category: project
  - 
    scope:
      type: posts
    values:
      permalink: blog/:title