version: '3' # specify docker-compose version

# Define the services/containers to be run
services:
  jekyll:
    build:
      context: .
      args:
        build_command: "jekyll serve --trace"
    volumes:
      - ".:/srv/jekyll:rw"
    ports:
      - 4000:4000
      - 35729:35729
